### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TheSharpieOne** [yornaath/batshit#1]
Can you please include a license. MIT would be nice :)

**Comment by yornaath** [comment]
Yes! Done ^^

**Comment by TheSharpieOne** [comment]
Thank! One note though: It looks like you copied the license from react-query, which attributes the copyright to react-query's author, "Tanner Linsley". You might want to update that to your name. Also, just so npm and other tooling can easily know what license is being used, you should add it to the `package.json` `license` for each package.

I opened a PR with these changes, if they are acceptable to you: #2
