### ISSUE TITLE
Feature: Group batch

### ISSUE THREAD

**Issue by burakgormek** [yornaath/batshit#18]
It would be good to have a way to group by parameters.

```js
const bob = users.fetch(1);
...
...
const alice = users.fetch(2, {date: new Date()});
```

**Comment by yornaath** [comment]
Not entirely sure what you mean. Can you explain in more detail?

**Comment by burakgormek** [comment]
```js
const users = create({
  fetcher: async (ids: number[]) => {
    return client.users.where({
      userId_in: ids,
    });
  },
  resolver: keyResolver("id"),
  scheduler: windowScheduler(10),
});
```
```js
const users1 = users.fetch(1, {date: "today"});
const users2 = users.fetch(2, {date: "today"});

const users3 = users.fetch(3, {date: "yesterday"});
const users4 = users.fetch(4, {date: "yesterday"});
```

I want to group users by date and make the fetcher run for each of group.
Currently, there is no way to pass filter like date and run fetcher multiple times for each group.
I have to manually create new batches for each group.

It would be good if we have group key and make the fetcher run for each group.
```js
const users = create({
  fetcher: async (ids: number[], date: string) => {
    return client.users.where({
      userId_in: ids,
      startDate: date,
    });
  },
  group: "date",
  resolver: keyResolver("id"),
  scheduler: windowScheduler(10),
});
```

**Comment by yornaath** [comment]
Ok yeah I get what you want, but whats the impetus for the request? Im not sure about what benefit it provides?

**Comment by yornaath** [comment]
Im not sure if this pattern is generalizable enough to warrent being part of the the core api of this library. Personally what I would do here is use memoization pr group.

```ts
const batcher = memoize((date: 'today' | 'yesterday') => {
  return create({
    fetcher: async (ids: number[]) => {
      return client.datapoints.where({
        idIn: ids,
        startDate: date,
      });
    },
    resolver: keyResolver("id"),
    scheduler: windowScheduler(10),
  });
})

batcher('today').fetch(1);
batcher('today').fetch(2);
batcher('yesterday').fetch(1);
batcher('yesterday').fetch(1);
```

**Comment by burakgormek** [comment]
Hmm, you're right. I wasn't confident either, so memoization seems more solid now.
I think adding this to the README will be helpful to others as well.

Thank you for your time.
