### ISSUE TITLE
Typescript non-array responses

### ISSUE THREAD

**Issue by TheSharpieOne** [yornaath/batshit#3]
Thanks for the awesome library. I was adding some typescript typings through the generics and noticed that it expects an array to be returned by the fetcher. In the README example (copied below for convenience) the user is an object with an `id` and a `name` and I am guessing the `client.users.where(...)` function would return an array of those user objects `[{id: 1, name: 'yornaath'}, {id: 2, name: 'TheSharpieOne'}]`. That is great
```
type User = { id: number; name: string };

const users = create<User, number>({
  fetcher: async (ids) => {
    return client.users.where({
      id_in: ids,
    });
  },
  resolver: keyResolver("id"),
  scheduler: windowScheduler(10), // Default and can be omitted.
});
```

But what if the API was returning an object with the keys being the `id`s that were searched `{1: {id: 1, name: 'yornaath'}, 2: {id: 2, name: 'TheSharpieOne'}}`. Yes, the ids are kind of duplicated in the response. I was trying to match the example, this is not my exact use-case... so thus more generically: an response object containing _more_ data based on some query params that can be combined together.

The restriction on expecting the result to be an array only seems to apply to `keyResolver`; which does a `.find`. Nowhere else does the type seem to matter / need to be an array. Maybe `keyResolver` can check for array vs object and attempt to use the value as the object key.

Perhaps the array can be added by the dev-user if they expect an array to be returned. Making the example above be `const users = create<User[], number>({` That seems like a breaking type change, but it also seems better than having `T[] | T` through the code since it's not as explicit.

**Comment by yornaath** [comment]
That is a very good point! Will see if I can make a easy fix for it asap ^^

**Comment by Anchakor** [comment]
I was thinking about this in a context of calling a bulk API which fetches a collection of items based on keys which multiple can map to an item - say fetching papers written by the specified authors, while some authors might have collaborated on the same papers (aka not doing `[].find()` but `[].where()`).

I think it's a question where the responsibility of parsing out the response should be - if in fetcher or resolver. Now it's bit in a middle way - I see there could be 2 APIs:

1. Very simple `create<TData, TKey>` where `resolver` doesn't exist and it's a responsibility of the `fetcher` to return `Promise<Record<TKey, TData>>`.
2. A bit more intuitive `create<TData, TKey, TResponse>` where `resolver` has type `(response: TResponse, key: TKey`) => TData`. This is nicer that you have more freedom of how `TKey` looks and don't need to do data manipulation in `fetcher`.

**Comment by Anchakor** [comment]
BTW it also could be nice to mention in the docs that if you want to enforce a max size of a batch API call, you can do it fetcher by
```ts
const results = await Promise.all(splitArray(keys, batchSize).map(execute));
return results.flat();
```

**Comment by yornaath** [comment]
@Anchakor For bulk fetching, isnt this exactly what you mean? https://github.com/yornaath/batshit#custom-batch-resolver

**Comment by yornaath** [comment]
@TheSharpieOne I made the item type generic T with no constraints, see this example for a use case where the response is an object: https://github.com/yornaath/batshit#custom-batch-resolver

Keep in mind that the resolver can be any function that maps the result T to type R, so it should be quite flexible in therms of bulk fetching, and mapping responses without having to massage the data in the fetcher.

**Comment by TheSharpieOne** [comment]
Awesome, thanks for doing this!

**Comment by Anchakor** [comment]
> @Anchakor For bulk fetching, isnt this exactly what you mean? https://github.com/yornaath/batshit#custom-batch-resolver

Yes, but i got held on the same issue that my fetcher didn't return a collection of fetch results, but an object. I isn't quite intuitive to post-process the fetch results in fetcher itself when there is something named "resolved". This fix changes it so thanks! Though I have to note that the documentation of the Generic type params is incorrect and lacking: https://github.com/yornaath/batshit/blob/6926bb66d272ef7803a23e590bfd0a7cbaa5ba4d/packages/batshit/src/index.ts#L9

**Comment by yornaath** [comment]
@Anchakor Yeah I didnt make my due dilligence and update the generic documentation after the fix. I will see if I can get around to it later this week. Or if you want to make a pr for it Im more than happy to review it and include it :D
