### ISSUE TITLE
Is the name intentional?

### ISSUE THREAD

**Issue by tbowmo** [yornaath/batshit#4]
I don't know how safe I feel, by including a library in my projects that refers to bat poop :)

Is it intentionally called batshit? Or is it just a typo?

**Comment by yornaath** [comment]
Its just a pun on "batch it" man ^^

**Comment by tbowmo** [comment]
Still has a bit of a bad ring to it..

**Comment by yornaath** [comment]
![ok bruv](https://blog.nukemberg.com/img/opinion.jpg)
