### ISSUE TITLE
How to limit the number of merge requests

### ISSUE THREAD

**Issue by linhleedom** [yornaath/batshit#6]
I want to limit the number of merge requests. 

Ex: I want to get details of 100 posts, and in scheduler =10ms, batshit will batch about 20-30 requests into one request. But I want to In a batch, it only batches up to 8 requests at a time, instead of combining all requests within 10ms.

Then instead of having 1 request with 20 postIds, I will have 3 requests with 

- **Request 1**: 8 postId, 
- **Request 2**: 8 postId, 
- **Request 3**: 4 postId

**Comment by yornaath** [comment]
Do you mean that if you set up one batcher and call `.fetch` on it a `100` times within `10ms` that it makes roughly 12 requests with a batch size of 8 for each request?

**Comment by yornaath** [comment]
You could do something like this to stagger the batches, this approach should do one request pr 10 posts ish:
```ts
const postFetcher = batshit.create({ ... });

const PostList = (props: {postIds: number[]}) => {
  return (<>
  {
    props.postIds.map((postId, index) => 
      <Post key={postId} postId={postId} index={index}/>
    )
  }
</>)
}

const Post = (props: {postId: number, index: number}) => {
  const {data: post, isFetching} = useQuery(["post", props.postId], async () => {
    await delay(index)
    return postFetcher.fetch(props.postId)
  });

  return <div>
    {
      isFetching ? 
        <div>loading...</div> 
      : <h1>{post.title}</h1>
    }
  </div>
}```

**Comment by yornaath** [comment]
@linhleedom Did you find a solution?

**Comment by tbowmo** [comment]
I'm also up for a more elegant solution to limit number of "entityIds" that we submit in a single request. We have identified one example where we have 32.000 GUIDs in one api request (and the number is prone to grow further in the future).

Could we add an option to batshit, so that one could define a max length of the id array, at which it fires off the api request, and start a new (10ms) timer?

**Comment by yornaath** [comment]
Linked a possible solution in the pr mentioned above this comment.
Please let me know what you think @tbowmo @linhleedom

_Note: changes are not yet published to npm._

**Comment by tbowmo** [comment]
@yornaath looks good for me :)

(In the mean time I found out that it's react-query that can't handle 32.000 ids, it simply crashes the browser, so a batch limit wont help here)

**Comment by linhleedom** [comment]
@yornaath looks good to me. Can you publish the change to npm? 

I had to copy your logic code into the project and overwrite it. This should not be done.
Thanks for the update
