### ISSUE TITLE
compile targets

### ISSUE THREAD

**Issue by tbowmo** [yornaath/batshit#7]
In one project I have problems importing the library due to the compiled targets. We use webpack 4.x (yep, it's an old one), and it doesn't like optional chaining in the generated js files (babel/acorn has issues)

Unfortunately I can not update webpack right now (time / complexity etc). So is it possible to look at the target settings, when building npm packages?

```
ERROR in /home/tbowmo/projects/FrontEnd/node_modules/@yornaath/batshit/dist/index.esm.js 14:30
Module parse failed: Unexpected token (14:30)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| const create = (config, memory) => {
>     const name = config.name ?? `batcher:${Math.random().toString(16).slice(2)})`;
|     const scheduler = config.scheduler ?? windowScheduler(10);
|     const devtools = globalThis.__BATSHIT_DEVTOOLS__?.for(name);
```

**Comment by tbowmo** [comment]
Found a workaround in our babel loader setup, using [this](https://webpack.js.org/loaders/babel-loader/#some-files-in-my-node_modules-are-not-transpiled-for-ie-11) as a guide

**Comment by yornaath** [comment]
Ok cool. Good you found a solution. Dont really feel like have to much backward compatt support for older build proccesses/versions of ecmascript.
